version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=wer08
      - POSTGRES_PASSWORD=Password
  frontend:
    build:
      context: ./frontend  # Use the current directory to build the Angular app container
      dockerfile: Dockerfile  # Specify the Dockerfile name
    ports:
      - "4200:80"  # Map port 8080 on the host to port 80 on the container
    restart: always  # Automatically restart the container if it stops
  backend:
    build: ./backend/backend
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=wer08
      - SPRING_DATASOURCE_PASSWORD=Password


